dashbitco/broadway_rabbitmq

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs
test/broadway_rabbitmq/producer_test.exs

* It doesn't actually validates RabbitMQ options since they will be validated by the amqp client. What it does is to make sure unsupported options are not accepted.
* Documentation does not list all RabbitMQ options avaiable. Instead it points to the amqp client documentation where all options are described
Closes #1 and #4

Validate supported options and update docs

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
lib/broadway_rabbitmq/rabbitmq_client.ex
mix.exs
test/broadway_rabbitmq/ampq_client_test.exs
test/broadway_rabbitmq/producer_test.exs

* Remove options
* Don't call `Queue.declare/3`
* Let it crash if the queue doesn't exist
Closes #13

Remove declare options

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs

This is a continuation @polymetis's work from #18. I opened a new PR in hope that this could be part of a new release.

Allow passing RabbitMQ connection options via an AMQP URI

---

lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/producer_test.exs

Closes #21.
This also makes :buffer_size a required option if :prefetch_count is set to 0.

Allow overriding :buffer_size and :buffer_keep

---

README.md

I've updated the readme with information and a simple example of the new `metadata` parameter.

Add metadata in Readme

---

lib/broadway_rabbitmq/producer.ex

The error appears when RabbitMQ connection goes down in runtime after the application was successfully started. Without handling it will crash the supervisor it's linked to

Add handling for unexpected connection close

---

lib/broadway_rabbitmq/producer.ex

Got this error this morning. I don't know if there is a better way to handle this.

fix: Handles an unknown host error

---

lib/broadway_rabbitmq/amqp_client.ex
test/broadway_rabbitmq/ampq_client_test.exs

The `:no_wait` and `:arguments` options for the `declare/4` function are allowed by the amqp library, however, they were not exposed in the documentation until [recently][1].
I've also changed the validation on `:nowait` binding opts to `:no_wait`,
as that one looks to be the correct (and documented) one.
[1]: https://github.com/pma/amqp/commit/ff19505d7fbd61839a7c17f12ae1758961f87e8e

Sync queue options with amqp allowed opts

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs

Closes #36.
This allows us to do something like:
```elixir
urls = [
"amqp://127.0.0.1",
"amqp://127.0.0.2"
]
{BroadwayRabbitMQ.Producer, connection: &Enum.at(urls, rem(&1, 2))}
```
**Note**: for this to work, Broadway master is required (as support for `:broadway_index` was introduced in https://github.com/plataformatec/broadway/pull/113.
\cc @msaraiva @josevalim

Add support for a function as the :connection

---

lib/broadway_rabbitmq/rabbitmq_client.ex

init returns a 2-elem tuple, not a 3-elem one

Fix RabbitmqClient behaviour typespec

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs
test/broadway_rabbitmq/producer_test.exs

cc @josevalim @msaraiva 
As discussed with @josevalim. Most of the reasoning is that we don't want to have our producer always try to reconnect to the same URL, so this way we can do random URL on every client reconnect or possibly do even round robin by using eg `persistent_term` or `counter` to store the currently used URL. After working on this, I think it might be beneficial to just support a list of URLs/options as the `:connection` option (or introduce `:connections`) just so that we can have round-robin built-in, but your call :)

Re-initialize client options on every reconnect

---

lib/broadway_rabbitmq/producer.ex

Recently ran into this error when running this in production trying to connect to a cloudamqp instance, and was resulting in a unmatched clause exception being raised.

fix: handle {:error, :not_allowed} connection issue

---

lib/broadway_rabbitmq/producer.ex

We weren't logging the reason of the failed connection before and we were failing with a bad error for unhandled reasons.

Improve logging of failed connections

---

lib/broadway_rabbitmq/rabbitmq_client.ex
test/broadway_rabbitmq/producer_test.exs

Im the implementation (`AMQPClient`) the queue is get from config: https://github.com/dashbitco/broadway_rabbitmq/blob/78cb281c9a3f7f8b0a81938dc3ec4cafb5449b69/lib/broadway_rabbitmq/amqp_client.ex#L99 
Has the option to change the `consume/2` to accept the queue direct instead of pass the config

Fix consume/2 callback

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs

Closes #57.
This PR doesn't test that we actually call the `:after_connect` option but that's because we have a "mock" for the whole `setup_channel/1` function, so we skip testing of all the calls to `AMQP.*` functions. I'll fix that in another PR but the code here is very straightforward luckily :)
cc @josevalim I would love a pair of :eyes: on this! 🙏

Add support for the :after_connect option

---

lib/broadway_rabbitmq/amqp_client.ex

I need to use amqp auth_mechanisms for external authentication, but they are not supported by `BroadwayRabbitMQ.AmqpClient`.
This adds `auth_mechanisms` to the supported connection options.

Add auth_mechanisms to supported connection options

---

lib/broadway_rabbitmq/amqp_client.ex

Moves the Keyword.merge into the validation. Makes the init function easier to follow.
The Keyword.merge is probably behaviour that belongs in the merge validation. This change makes the code easier to follow. Plus I think it's conventional to return opts so that you can continue piping them through validations anyways.
It should be pointed out that @whatyouhide [added a bunch of tests for merge_opts](https://github.com/dashbitco/broadway_rabbitmq/blob/b99105ddcd133d5bf4ba3122b31dc6ba803e905b/test/broadway_rabbitmq/ampq_client_test.exs#L146) and they still pass so I think it's safe to merge.  
Seems to have failed for some hex related reason, but I'm not sure how to re-run the test.

Return opts from the merge validation

---

lib/broadway_rabbitmq/amqp_client.ex

Move supported declare options to top of module
It makes it easier to understand what the supported declare options are if they're at the top of the module.
Basically the same as https://github.com/dashbitco/broadway_rabbitmq/pull/65.

Move supported declare options to top of module

---

lib/broadway_rabbitmq/amqp_client.ex

Move supported qos options to top of module.
Move supported bindings options to top of module.
Makes it easier to read and follows the convention of the other validations. 
Sorry for creating so many of these PR's. I should've done them in all in one go, but I'm finding them as I read through the code. This should be the last one.

Move supported qos options and bindings options to top of module

---

lib/broadway_rabbitmq/producer.ex

I included broadway_rabbitmq in my project and I needed to read the headers of the messages being consumed. I couldn't find how to do it in the documentation, then I saw this issue ( #29 ) and decided to help

chore: Updating BroadwayRabbitMQ.Producer moduledoc to included information about metadata

---

CHANGELOG.md
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/producer_test.exs

This is meant to prompt users to consider the tradeoffs of the available
options, especially the possibility of an infinite number of retries
when using `:reject_and_requeue`

Deprecate use of default :on_failure option

---

lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/producer_test.exs

Doing `Logger.error(Exception.format(...))` is confusing because it looks exactly like a crash, but we are trapping it, so it's not really "a crash". I rephrased the logging, what do you folks think?
I took the chance to have a bit more logging in place in general.

Add more logging in the producer

---

lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/producer_test.exs

Allows us to do things such as publish messages back to RabbitMQ and stuff like that by reusing the existing connection and channel. One thing I’m not sure about is if I should mention somewhere in the docs that you shouldn't "mess" with this channel in order to avoid screwing up the producer, but maybe folks will get it just fine? :)

Include AMQP channel in the message metadata

---

lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/producer_test.exs

Please refer to https://github.com/dashbitco/broadway/issues/208 for further background.
`BrowadwayRabbitMQ.Producer.ack_messages/3` both swallows errors that get thrown during message acknowledgement and ignores [the error tuple that `amqp` returns if something went wrong](https://github.com/pma/amqp/blob/master/lib/amqp/basic.ex#L135-L138). This means that if a consumer tries to acknowledge receipt of a message before processing it, but an error occurs during the acknowledgement, messages will get double-processed.
Here we raise the errors after logging and explicitly handle the error tuples from `amqp`.

Raise if acking a message fails

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs
test/broadway_rabbitmq/producer_test.exs

We particularly need `no_ack: true` which is the only way to have guaranteed "at most once" processing with RabbitMQ. Seems fair enough to just set the acknowledger to `Broadway.NoopAcknowledger` when `:no_ack` is `true`.

Add support for consume options

---

mix.exs

As I mentioned [here](https://github.com/dashbitco/broadway_rabbitmq/issues/89), amqp 2.0 would be compatible with Broadway. No other changes required and you can continue supporting 1.x.

Support amqp 2.0

---

lib/broadway_rabbitmq/backoff.ex

The :random module is deprecated since OTP 19, and :rand is available
since OTP 18.

Remove usage of :random module

---

config/config.exs
mix.exs

Starting from amqp-3.0, lager will no longer be required 🎉
Tested by overriding the dep to allow amqp-3.0-rc.1 and running tests.
https://github.com/pma/amqp/wiki/3.0-Release-Notes

Support amqp-3.0

---

mix.exs

Updates nimble options dependency to allow 0.4.0
#110

Allow nimble_options 0.4.0

---

lib/broadway_rabbitmq/producer.ex

The existing example raises the following exception:
(ArgumentError) invalid configuration given to Broadway.start_link/2, required option :name not found, received options: [:producer, :processors]

Update code example for dead-letter exchanges

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
test/broadway_rabbitmq/ampq_client_test.exs

Improve error when acking on a closed channel

---

lib/broadway_rabbitmq/amqp_client.ex

The backoff options are repeated in the producer and the client. I think they are not used in the client, so I removed them

Remove unused backoff options from client

---

lib/broadway_rabbitmq/amqp_client.ex

when the provided module implement multiple behaviours, the check may fail depending in the order they are defined. this one fixes, this issue.

Fix validating behaviour when module implement multiple behaviours

---

lib/broadway_rabbitmq/amqp_client.ex
lib/broadway_rabbitmq/producer.ex
lib/broadway_rabbitmq/rabbitmq_client.ex
test/broadway_rabbitmq/ampq_client_test.exs
test/broadway_rabbitmq/producer_test.exs

`AmqpClient.close_connection/1` closes the connection independently if its using channel pool or not.
this causes a lot of errors on application shutdown when using channel pool.

Fix closing connection from channel pool

---

mix.exs

This change allows us to use broadway_rabbitmq with amqp version 4.x.
As per the [release notes](https://github.com/pma/amqp/wiki/4.0-Release-Notes), it has no breaking changes so no other change here is necessary.

refactor: Allow usage with amqp 4.x
